NO_FINK = 1
NO_DARWIN_PORTS = 1
NO_PERL = 1
NO_PERL_CPAN_FALLBACKS = 1
NO_GITWEB = 1
NO_PYTHON = 1
NO_TCLTK = 1
HAVE_NS_GET_EXECUTABLE_PATH = 1
# RUNTIME_PREFIX = 1
INSTALL_STRIP = -s
APPLE_COMMON_CRYPTO_SHA1 = 1
INSTALL_SYMLINKS = 1

#print-git-version:
#	@echo $(GIT_VERSION)